const AUTH_START = 'AUTH_START';
const AUTH_SUCCESS = 'AUTH_SUCCESS';
const AUTH_FAIL = 'AUTH_FAIL';
const AUTH_LOGOUT = 'AUTH_LOGOUT';
const AUTH_CALLBACK_START = 'AUTH_CALLBACK_START';
const AUTH_CALLBACK_SUCCESS = 'AUTH_CALLBACK_SUCCESS';
const AUTH_CALLBACK_FAIL = 'AUTH_CALLBACK_FAIL';
const UPDATE_REPOSITORY_DATA = 'UPDATE_REPOSITORY_DATA';
const REMOVE_REPOSITORY_DATA = 'REMOVE_REPOSITORY_DATA';
const HIDE_REPOSITORY_DATA = 'HIDE_REPOSITORY_DATA';
const SHOW_REPOSITORY_DATA = 'SHOW_REPOSITORY_DATA';

export default {
  AUTH_START,
  AUTH_SUCCESS,
  AUTH_FAIL,
  AUTH_CALLBACK_FAIL,
  AUTH_CALLBACK_SUCCESS,
  AUTH_CALLBACK_START,
  AUTH_LOGOUT,
  UPDATE_REPOSITORY_DATA,
  REMOVE_REPOSITORY_DATA,
  HIDE_REPOSITORY_DATA,
  SHOW_REPOSITORY_DATA,
};
