const AUTH_START = 'AUTH_START';
const AUTH_SUCCESS = 'AUTH_SUCCESS';
const AUTH_FAIL = 'AUTH_FAIL';
const AUTH_LOGOUT = 'AUTH_LOGOUT';
const AUTH_CALLBACK_START = 'AUTH_CALLBACK_START';
const AUTH_CALLBACK_SUCCESS = 'AUTH_CALLBACK_SUCCESS';
const AUTH_CALLBACK_FAIL = 'AUTH_CALLBACK_FAIL';

export default {
  AUTH_START,
  AUTH_SUCCESS,
  AUTH_FAIL,
  AUTH_CALLBACK_FAIL,
  AUTH_CALLBACK_SUCCESS,
  AUTH_CALLBACK_START,
  AUTH_LOGOUT,
};
