# Generated by Django 2.2.8 on 2019-12-13 03:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0003_auto_20191212_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='repositories.Contributor'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 3, 7, 45, 771, tzinfo=utc)),
        ),
    ]
