# Generated by Django 2.2.8 on 2019-12-13 03:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0004_auto_20191213_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 3, 9, 7, 199649, tzinfo=utc)),
        ),
    ]
