# Generated by Django 2.2.8 on 2019-12-13 03:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0005_auto_20191213_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='author',
        ),
        migrations.AddField(
            model_name='repository',
            name='organization',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repository',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 3, 12, 34, 84433, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
    ]
