# Generated by Django 2.2.8 on 2019-12-13 03:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0006_auto_20191213_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 3, 15, 16, 677216, tzinfo=utc)),
        ),
    ]
