# Generated by Django 2.2.8 on 2019-12-16 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0008_auto_20191216_0444'),
        ('repositories', '0008_auto_20191216_1820'),
    ]

    operations = [
    ]
